## ?????? ??????(???? ?? ???? ?????????? ???)
spring.application.name=spring-project1

## ???????? mysql????? ?? ???? mysql? ?????? ??? ???? ? ???
## ????? ????? ??????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## ????? ?? ??? ????????.
spring.datasource.url=jdbc:mysql://localhost:3306/backend_spring_project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
## jdbc:mysql:// ? mysql??? ?? ???? ??, 3306? ??????? ??
## localhost:8080 => ????? ?????? ?????
## localhost:3306 => ????? ?????? ??????????
spring.datasource.username=root
spring.datasource.password=

spring.mvc.view.prefix=/WEB-INF/views
spring.mvc.view.suffix=.jsp
## ????? /WEB-INF/views/index.jsp => "/index"

## swagger ??
## swagger API ??????
springdoc.api-docs.path=/v3/api-docs

## swagger UI ?? ??
## localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html

## swagger UI?? API? ???? ?? (???? ??)
springdoc.swagger-ui.operations-sorter=method